# https://docs.platformio.org/en/latest/integration/ci/travis.html#using-cmd-run-command

language: python
python:
  - "2.7"

cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_ENV=t85
  - PLATFORMIO_CI_ENV=m168
  - PLATFORMIO_CI_ENV=m328

install:
  - pip install -U platformio
  - pio update

script:
  - pio run -e $PLATFORMIO_CI_ENV
